version: "2.3"

networks:
  mattermost-ldap_external_network:
  mattermost-ldap_internal_network:
    internal: true

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      mattermost-ldap-db:
        condition: service_started
      mattermost-ldap:
        condition: service_started
      mattermost-ldap-nginx:
        condition: service_started
    networks:
      - mattermost-ldap_internal_network
    volumes_from:
      - mattermost-ldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  mattermost-ldap:
    # For development or CI, tag build from local Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        - TAG=${TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    # For production, download prebuilt image
    #image: ${IMAGE_NAME}
    container_name: mattermost-ldap
    #restart: always
    depends_on:
      mattermost-ldap-db:
        condition: service_healthy
    links:
      - mattermost-ldap-db
    expose:
      - '9000'
    #ports:
    #  - "9000:9000"
    networks:
      - mattermost-ldap_internal_network
    volumes:
      - $MATTERMOST-LDAP_HOME/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MATTERMOST-LDAP_DB_TYPE=pgsql
      - MATTERMOST-LDAP_DB_HOST=mattermost-ldap-db
      - MATTERMOST-LDAP_DB_NAME=$MATTERMOST-LDAP_DB_NAME
      - MATTERMOST-LDAP_DB_USER=$MATTERMOST-LDAP_DB_USER
      - MATTERMOST-LDAP_DB_PASSWORD=$MATTERMOST-LDAP_DB_PASSWD

  mattermost-ldap-db:
    image: postgres:latest
    container_name: mattermost-ldap-db
    restart: always
    #ports:
    #  - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${MATTERMOST-LDAP_DB_USER}", "-d", "${MATTERMOST-LDAP_DB_NAME}"]
    networks:
      - mattermost-ldap_internal_network
    volumes:
      - $MATTERMOST-LDAP_HOME/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_DB=$MATTERMOST-LDAP_DB_NAME
      - POSTGRES_USER=$MATTERMOST-LDAP_DB_USER
      - POSTGRES_PASSWORD=$MATTERMOST-LDAP_DB_PASSWD

  mattermost-ldap-nginx:
    image: nginx:latest
    container_name: mattermost-ldap-nginx
    restart: always
    ports:
      - "80:80"
      # If you need SSL connection
      # - "443:443"
    networks:
      - mattermost-ldap_internal_network
      - mattermost-ldap_external_network
    depends_on:
      mattermost-ldap:
        condition: service_started
    links:
      - mattermost-ldap
    volumes:
      - $MATTERMOST-LDAP_HOME/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # TODO Provide a custom nginx conf
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      # - NGINX_CGI=mattermost-ldap:9000 # same as mattermost-ldap container name
