version: "2.3"

networks:
  MATTERMOST_LDAP_external_network:
  MATTERMOST_LDAP_internal_network:
    internal: true

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      mattermost-ldap-db:
        condition: service_healthy
      mattermost-ldap:
        condition: service_started
    networks:
      - MATTERMOST_LDAP_internal_network
    volumes_from:
      - mattermost-ldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  mattermost-ldap:
    # For development or CI, tag build from local Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        - TAG=${TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    # For production, download prebuilt image
    #image: ${IMAGE_NAME}
    container_name: mattermost-ldap
    #restart: always
    depends_on:
      mattermost-ldap-db:
        condition: service_healthy
    links:
      - mattermost-ldap-db
    expose:
      - '80'
    ports:
      - "80:80"
    networks:
      - MATTERMOST_LDAP_internal_network
      - MATTERMOST_LDAP_external_network
    volumes:
      - $HOME/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MATTERMOST_LDAP_DB_TYPE=mysql
      - MATTERMOST_LDAP_DB_HOST=$mattermost-ldap-db
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - MATTERMOST_LDAP_DB_PASSWORD=$DB_PASS

  mattermost-ldap-db:
    image: mariadb:latest
    container_name: mattermost-ldap-db
    restart: always
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=${$DB_ROOT_PASSWD}"]
      timeout: 10s
      retries: 5
    expose:
      - '3306'
    #ports:
    #  - "3306:3306"
    networks:
      - MATTERMOST_LDAP_internal_network
    volumes:
      - $HOME/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
